# Generated by Django 4.1.7 on 2023-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmanager',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
