# Generated by Django 4.1.7 on 2023-04-12 13:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0002_alter_bookmanager_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmanager',
            options={'verbose_name': 'Book Manager', 'verbose_name_plural': 'Book Manager'},
        ),
        migrations.AddField(
            model_name='type',
            name='days',
            field=models.PositiveIntegerField(default=30, verbose_name='Насколько выдается'),
        ),
        migrations.AlterField(
            model_name='bookmanager',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lib_manager.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookmanager',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='bookmanager',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='bookmanager',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
